### PR TITLE
Implement a prefix for uploading to S3

### LINKED ISSUE #7: create project folder in S3 bucket
We need to use one S3 bucket for different LAMDA functions. Currently the plugin only creates a flat hierarchy of version folders.

### PR DESCRIPTION
**Pull request by esc**
Closes #7

### CODE REVIEW

**Comment by esc** [comment]
@mlefringhausen would this solve your issue?

**Comment by esc** [comment]
@sneben care to review?

**Comment by mlefringhausen** [comment]
Looks good! Thanks for the fast solution.

**Comment by esc** [comment]
Cool, I'll merge now and a new version should be available via PyPI shortly thereafter. Please do test it and report back an issues you might have.

**Comment by mlefringhausen** [comment]
works perfect!

**Pull request merged**
